export default function TermsOfServicePage() {
  return (
    <div className="container max-w-4xl py-12">
      <h1 className="text-4xl font-bold tracking-tight mb-4">Terms of Service</h1>
      <p className="text-muted-foreground mb-8">
        Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
      </p>

      <div className="prose prose-slate dark:prose-invert max-w-none">
        <h2>Agreement to Terms</h2>
        <p>
          By accessing or using NeonHub ("Service"), you agree to be bound by these Terms of Service ("Terms").
          If you disagree with any part of these Terms, you may not access the Service.
        </p>

        <h2>Description of Service</h2>
        <p>
          NeonHub is an AI-powered SEO and content marketing platform that provides:
        </p>
        <ul>
          <li>Keyword research and discovery tools</li>
          <li>AI content generation with brand voice alignment</li>
          <li>Internal linking suggestions using semantic analysis</li>
          <li>SEO analytics and performance tracking</li>
          <li>Trend detection and content recommendations</li>
          <li>Integration with third-party services (Google Search Console, social platforms)</li>
        </ul>

        <h2>Account Registration</h2>
        <ul>
          <li>You must provide accurate, complete information during registration</li>
          <li>You're responsible for maintaining account security (strong passwords, 2FA recommended)</li>
          <li>You must be at least 16 years old to use the Service</li>
          <li>One person or legal entity may not maintain multiple free accounts</li>
          <li>We reserve the right to refuse service or terminate accounts for violations</li>
        </ul>

        <h2>Acceptable Use Policy</h2>
        
        <h3>You May:</h3>
        <ul>
          <li>Use the Service for lawful business purposes</li>
          <li>Generate content for your own websites and marketing</li>
          <li>Connect authorized third-party accounts (GSC, social platforms)</li>
          <li>Export your data at any time</li>
        </ul>

        <h3>You May Not:</h3>
        <ul>
          <li>Use the Service to create spam, malware, or illegal content</li>
          <li>Attempt to circumvent usage limits or security measures</li>
          <li>Scrape, reverse engineer, or access the Service through automated means (except our API)</li>
          <li>Impersonate others or misrepresent your affiliation</li>
          <li>Violate intellectual property rights or publish confidential information</li>
          <li>Use the Service to harm, harass, or defame others</li>
        </ul>

        <h2>Intellectual Property</h2>
        
        <h3>Your Content</h3>
        <p>
          You retain ownership of content you create using NeonHub. By using the Service, you grant us a
          limited license to process, store, and display your content as necessary to provide the Service.
        </p>

        <h3>NeonHub Platform</h3>
        <p>
          NeonHub owns all rights to the platform, including software, algorithms, UI/UX, and documentation.
          You may not copy, modify, or create derivative works without permission.
        </p>

        <h3>AI-Generated Content</h3>
        <p>
          Content generated by our AI tools is provided to you for use. We don't claim ownership, but you're
          responsible for ensuring it complies with applicable laws and doesn't infringe third-party rights.
          Always review and edit AI-generated content before publishing.
        </p>

        <h2>Subscription & Payments</h2>
        <ul>
          <li><strong>Free Tier:</strong> Limited usage for evaluation purposes</li>
          <li><strong>Paid Plans:</strong> Billed monthly or annually via Stripe</li>
          <li><strong>Refunds:</strong> Pro-rated refunds within 14 days of upgrade (discretionary)</li>
          <li><strong>Cancellation:</strong> Cancel anytime; access continues until end of billing period</li>
          <li><strong>Price Changes:</strong> 30-day notice for existing subscribers</li>
        </ul>

        <h2>Service Availability & Support</h2>
        <ul>
          <li><strong>Uptime:</strong> We strive for 99.9% uptime (no guarantee)</li>
          <li><strong>Maintenance:</strong> Scheduled downtime announced 24 hours in advance</li>
          <li><strong>Support:</strong> Email support for paid plans, community forum for free tier</li>
          <li><strong>Response Time:</strong> 24-48 hours for support inquiries</li>
        </ul>

        <h2>API Usage & Rate Limits</h2>
        <p>
          If you use our API:
        </p>
        <ul>
          <li>Rate limits apply based on your plan tier</li>
          <li>Excessive usage may result in temporary throttling</li>
          <li>API keys must be kept confidential</li>
          <li>Breaking changes announced 30 days in advance</li>
        </ul>

        <h2>Disclaimers & Limitations of Liability</h2>
        <p>
          <strong>No Warranties:</strong> The Service is provided "as is" without warranties of any kind.
          We don't guarantee that AI-generated content will rank in search engines or achieve specific results.
        </p>
        <p>
          <strong>Limitation of Liability:</strong> Our liability is limited to the amount you paid in the
          past 12 months. We're not liable for indirect, consequential, or punitive damages.
        </p>
        <p>
          <strong>Third-Party Services:</strong> We're not responsible for third-party integrations
          (Google, social platforms) or their availability.
        </p>

        <h2>Termination</h2>
        <p>
          We may suspend or terminate your account if you:
        </p>
        <ul>
          <li>Violate these Terms or our Acceptable Use Policy</li>
          <li>Fail to pay (for paid accounts)</li>
          <li>Engage in fraudulent or illegal activity</li>
          <li>Pose a security risk to the platform or other users</li>
        </ul>
        <p>
          Upon termination, you have 30 days to export your data. After that, it may be permanently deleted.
        </p>

        <h2>Indemnification</h2>
        <p>
          You agree to indemnify NeonHub against claims arising from your use of the Service, including
          your content, violation of these Terms, or infringement of third-party rights.
        </p>

        <h2>Governing Law & Dispute Resolution</h2>
        <ul>
          <li><strong>Governing Law:</strong> Laws of [Your Jurisdiction]</li>
          <li><strong>Arbitration:</strong> Disputes resolved through binding arbitration (unless small claims court)</li>
          <li><strong>Class Action Waiver:</strong> No class actions or representative proceedings</li>
          <li><strong>Venue:</strong> [Your Jurisdiction] for any litigation</li>
        </ul>

        <h2>Changes to Terms</h2>
        <p>
          We may update these Terms to reflect changes in our Service or legal requirements.
          We'll notify you via email for material changes. Continued use after changes constitutes acceptance.
        </p>

        <h2>Contact & Legal Notices</h2>
        <p>
          For questions about these Terms:
        </p>
        <ul>
          <li><strong>Email:</strong> <a href="mailto:legal@neonhub.ai">legal@neonhub.ai</a></li>
          <li><strong>Address:</strong> NeonHub Legal Department, [Your Business Address]</li>
        </ul>

        <h2>Severability</h2>
        <p>
          If any provision of these Terms is found unenforceable, the remaining provisions remain in effect.
        </p>

        <div className="mt-12 p-6 bg-muted rounded-lg">
          <h3 className="text-lg font-semibold mb-2">Built for Creators. Protected by Law.</h3>
          <p className="text-sm text-muted-foreground">
            These Terms are designed to protect both you and NeonHub. We're committed to fair,
            transparent practices that empower your content marketing. Questions? Reach out anytime.
          </p>
        </div>

        <div className="mt-6">
          <p className="text-sm text-muted-foreground">
            <strong>Note:</strong> This is a template. Consult with a licensed attorney to customize for your
            jurisdiction and business model before public launch.
          </p>
        </div>
      </div>
    </div>
  );
}
