import OpenAI from "openai";
import { getEnv } from "../config/env.js";
import { logger } from "../lib/logger.js";

const env = getEnv();

let openai: OpenAI | null = null;
const isMockMode = !env.OPENAI_API_KEY;

if (!isMockMode) {
  openai = new OpenAI({
    apiKey: env.OPENAI_API_KEY,
  });
} else {
  logger.warn("⚠️ OpenAI API key not found. Running in MOCK mode.");
}

export interface GenerateTextOptions {
  prompt: string;
  model?: string;
  temperature?: number;
  maxTokens?: number;
  systemPrompt?: string;
}

export interface GenerateTextResult {
  text: string;
  usage?: {
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
  };
  model: string;
  mock: boolean;
}

/**
 * Generate text using OpenAI API with retry logic
 * Falls back to mock mode if API key is missing
 */
export async function generateText(options: GenerateTextOptions): Promise<GenerateTextResult> {
  const {
    prompt,
    model = env.OPENAI_MODEL || "gpt-4",
    temperature = 0.7,
    maxTokens = 1500,
    systemPrompt = "You are a helpful AI assistant specialized in creating marketing content.",
  } = options;

  // Mock mode
  if (isMockMode || !openai) {
    logger.info({ prompt: prompt.substring(0, 100) }, "Generating text (MOCK mode)");
    
    await new Promise((resolve) => setTimeout(resolve, 500)); // Simulate API delay
    
    return {
      text: generateMockContent(prompt),
      model: "mock-gpt-4",
      mock: true,
    };
  }

  // Real OpenAI API call with retry logic
  const maxRetries = 3;
  let lastError: Error | null = null;

  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      logger.info({ attempt, model, promptLength: prompt.length }, "Calling OpenAI API");

      const startTime = Date.now();
      const completion = await openai.chat.completions.create({
        model,
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: prompt },
        ],
        temperature,
        max_tokens: maxTokens,
      });

      const duration = Date.now() - startTime;
      const text = completion.choices[0]?.message?.content || "";

      logger.info({
        duration,
        tokens: completion.usage?.total_tokens,
        model: completion.model,
      }, "OpenAI API call successful");

      return {
        text,
        usage: completion.usage ? {
          promptTokens: completion.usage.prompt_tokens,
          completionTokens: completion.usage.completion_tokens,
          totalTokens: completion.usage.total_tokens,
        } : undefined,
        model: completion.model,
        mock: false,
      };
    } catch (error) {
      lastError = error as Error;
      logger.warn({
        error: lastError.message,
        attempt,
        maxRetries,
      }, "OpenAI API call failed");

      if (attempt < maxRetries) {
        const backoff = Math.pow(2, attempt) * 1000; // Exponential backoff
        await new Promise((resolve) => setTimeout(resolve, backoff));
      }
    }
  }

  // All retries failed, log error and throw
  logger.error({ error: lastError }, "OpenAI API call failed after all retries");
  throw new Error(`OpenAI API call failed: ${lastError?.message || "Unknown error"}`);
}

/**
 * Generate mock content for testing/demo purposes
 */
function generateMockContent(prompt: string): string {
  const promptLower = prompt.toLowerCase();
  
  if (promptLower.includes("blog") || promptLower.includes("article")) {
    return `# AI-Generated Blog Post (Mock Mode)

## Introduction
This is a mock-generated blog post created for demonstration purposes. In production, this content would be generated by OpenAI's GPT-4 model based on your specific requirements.

## Key Points
- **Point 1**: AI-powered content generation enables rapid content creation
- **Point 2**: Modern marketing requires consistent, high-quality content
- **Point 3**: Automation tools can help teams scale their content efforts

## Detailed Analysis
The use of AI in content marketing has revolutionized how businesses approach their content strategy. By leveraging advanced language models, companies can now generate high-quality drafts that maintain brand voice while significantly reducing production time.

## Conclusion
As AI technology continues to evolve, the integration of automated content generation tools will become increasingly essential for competitive marketing operations.

---
*Note: This is mock content. Configure OPENAI_API_KEY for real AI generation.*`;
  }

  if (promptLower.includes("social") || promptLower.includes("post")) {
    return `🚀 Exciting news! AI-powered content generation is transforming how we create engaging marketing materials.

✨ Key benefits:
• 10x faster content creation
• Consistent brand voice
• Data-driven optimization

Ready to revolutionize your content strategy? Let's connect! 💡

#AI #Marketing #ContentCreation #Innovation

---
*Mock content - Enable OpenAI for real generation*`;
  }

  if (promptLower.includes("email")) {
    return `Subject: Welcome to Our Platform!

Hi there,

We're thrilled to have you join our community! This is a mock email generated for demonstration purposes.

In production, this would be a personalized email created by our AI system based on your specific requirements, audience, and brand voice.

**What's Next:**
1. Complete your profile setup
2. Explore our features
3. Connect with our team

Looking forward to helping you succeed!

Best regards,
The Team

---
*Mock email - Configure OpenAI for personalized generation*`;
  }

  // Generic mock content
  return `This is AI-generated content (mock mode) based on your prompt:

"${prompt.substring(0, 200)}${prompt.length > 200 ? "..." : ""}"

**In production mode**, this would be replaced with high-quality content generated by OpenAI's GPT-4 model, tailored to your specific requirements, tone, and audience.

**To enable real AI generation:**
1. Add your OPENAI_API_KEY to backend/.env
2. Restart the backend server
3. Generate content again

---
*Mock content for demo purposes*`;
}

export function isInMockMode(): boolean {
  return isMockMode;
}
