import { z } from 'zod';
type EnvSchema = z.ZodObject<{
    DATABASE_URL: z.ZodString;
    NEXTAUTH_SECRET: z.ZodString;
    NEXTAUTH_URL: z.ZodString;
    CORS_ORIGINS: z.ZodEffects<z.ZodString, string[], string>;
    REDIS_URL: z.ZodOptional<z.ZodString>;
    STRIPE_SECRET_KEY: z.ZodString;
    STRIPE_WEBHOOK_SECRET: z.ZodString;
    RESEND_API_KEY: z.ZodString;
    OPENAI_API_KEY: z.ZodString;
    OPENAI_MODEL: z.ZodDefault<z.ZodString>;
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "production", "test"]>>;
    PORT: z.ZodDefault<z.ZodNumber>;
    BETA_ENABLED: z.ZodDefault<z.ZodBoolean>;
    SENTRY_DSN: z.ZodOptional<z.ZodString>;
    TWILIO_ACCOUNT_SID: z.ZodOptional<z.ZodString>;
    TWILIO_SID: z.ZodOptional<z.ZodString>;
    TWILIO_AUTH_TOKEN: z.ZodOptional<z.ZodString>;
    TWILIO_PHONE_NUMBER: z.ZodOptional<z.ZodString>;
    TWITTER_BEARER_TOKEN: z.ZodOptional<z.ZodString>;
    REDDIT_CLIENT_ID: z.ZodOptional<z.ZodString>;
    REDDIT_CLIENT_SECRET: z.ZodOptional<z.ZodString>;
    REDDIT_USER_AGENT: z.ZodDefault<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    DATABASE_URL: string;
    NEXTAUTH_SECRET: string;
    NEXTAUTH_URL: string;
    CORS_ORIGINS: string[];
    STRIPE_SECRET_KEY: string;
    STRIPE_WEBHOOK_SECRET: string;
    RESEND_API_KEY: string;
    OPENAI_API_KEY: string;
    OPENAI_MODEL: string;
    NODE_ENV: "development" | "production" | "test";
    PORT: number;
    BETA_ENABLED: boolean;
    REDDIT_USER_AGENT: string;
    REDIS_URL?: string | undefined;
    SENTRY_DSN?: string | undefined;
    TWILIO_ACCOUNT_SID?: string | undefined;
    TWILIO_SID?: string | undefined;
    TWILIO_AUTH_TOKEN?: string | undefined;
    TWILIO_PHONE_NUMBER?: string | undefined;
    TWITTER_BEARER_TOKEN?: string | undefined;
    REDDIT_CLIENT_ID?: string | undefined;
    REDDIT_CLIENT_SECRET?: string | undefined;
}, {
    DATABASE_URL: string;
    NEXTAUTH_SECRET: string;
    NEXTAUTH_URL: string;
    CORS_ORIGINS: string;
    STRIPE_SECRET_KEY: string;
    STRIPE_WEBHOOK_SECRET: string;
    RESEND_API_KEY: string;
    OPENAI_API_KEY: string;
    REDIS_URL?: string | undefined;
    OPENAI_MODEL?: string | undefined;
    NODE_ENV?: "development" | "production" | "test" | undefined;
    PORT?: number | undefined;
    BETA_ENABLED?: boolean | undefined;
    SENTRY_DSN?: string | undefined;
    TWILIO_ACCOUNT_SID?: string | undefined;
    TWILIO_SID?: string | undefined;
    TWILIO_AUTH_TOKEN?: string | undefined;
    TWILIO_PHONE_NUMBER?: string | undefined;
    TWITTER_BEARER_TOKEN?: string | undefined;
    REDDIT_CLIENT_ID?: string | undefined;
    REDDIT_CLIENT_SECRET?: string | undefined;
    REDDIT_USER_AGENT?: string | undefined;
}>;
export type Env = z.infer<EnvSchema>;
export declare function validateEnv(): Env;
export declare const env: {
    DATABASE_URL: string;
    NEXTAUTH_SECRET: string;
    NEXTAUTH_URL: string;
    CORS_ORIGINS: string[];
    STRIPE_SECRET_KEY: string;
    STRIPE_WEBHOOK_SECRET: string;
    RESEND_API_KEY: string;
    OPENAI_API_KEY: string;
    OPENAI_MODEL: string;
    NODE_ENV: "development" | "production" | "test";
    PORT: number;
    BETA_ENABLED: boolean;
    REDDIT_USER_AGENT: string;
    REDIS_URL?: string | undefined;
    SENTRY_DSN?: string | undefined;
    TWILIO_ACCOUNT_SID?: string | undefined;
    TWILIO_SID?: string | undefined;
    TWILIO_AUTH_TOKEN?: string | undefined;
    TWILIO_PHONE_NUMBER?: string | undefined;
    TWITTER_BEARER_TOKEN?: string | undefined;
    REDDIT_CLIENT_ID?: string | undefined;
    REDDIT_CLIENT_SECRET?: string | undefined;
};
export declare const getEnv: () => {
    DATABASE_URL: string;
    NEXTAUTH_SECRET: string;
    NEXTAUTH_URL: string;
    CORS_ORIGINS: string[];
    STRIPE_SECRET_KEY: string;
    STRIPE_WEBHOOK_SECRET: string;
    RESEND_API_KEY: string;
    OPENAI_API_KEY: string;
    OPENAI_MODEL: string;
    NODE_ENV: "development" | "production" | "test";
    PORT: number;
    BETA_ENABLED: boolean;
    REDDIT_USER_AGENT: string;
    REDIS_URL?: string | undefined;
    SENTRY_DSN?: string | undefined;
    TWILIO_ACCOUNT_SID?: string | undefined;
    TWILIO_SID?: string | undefined;
    TWILIO_AUTH_TOKEN?: string | undefined;
    TWILIO_PHONE_NUMBER?: string | undefined;
    TWITTER_BEARER_TOKEN?: string | undefined;
    REDDIT_CLIENT_ID?: string | undefined;
    REDDIT_CLIENT_SECRET?: string | undefined;
};
export {};
//# sourceMappingURL=env.d.ts.map
