import { z } from 'zod';
declare const envSchema: z.ZodObject<{
    DATABASE_URL: z.ZodString;
    NEXTAUTH_SECRET: z.ZodString;
    NEXTAUTH_URL: z.ZodString;
    CORS_ORIGINS: z.ZodEffects<z.ZodString, string[], string>;
    STRIPE_SECRET_KEY: z.ZodString;
    STRIPE_WEBHOOK_SECRET: z.ZodString;
    RESEND_API_KEY: z.ZodString;
    OPENAI_API_KEY: z.ZodString;
    OPENAI_MODEL: z.ZodDefault<z.ZodString>;
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "production", "test"]>>;
    PORT: z.ZodDefault<z.ZodNumber>;
    SENTRY_DSN: z.ZodOptional<z.ZodString>;
    TWILIO_ACCOUNT_SID: z.ZodOptional<z.ZodString>;
    TWILIO_AUTH_TOKEN: z.ZodOptional<z.ZodString>;
    TWILIO_PHONE_NUMBER: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    DATABASE_URL: string;
    NEXTAUTH_SECRET: string;
    NEXTAUTH_URL: string;
    CORS_ORIGINS: string[];
    STRIPE_SECRET_KEY: string;
    STRIPE_WEBHOOK_SECRET: string;
    RESEND_API_KEY: string;
    OPENAI_API_KEY: string;
    OPENAI_MODEL: string;
    NODE_ENV: "development" | "production" | "test";
    PORT: number;
    SENTRY_DSN?: string | undefined;
    TWILIO_ACCOUNT_SID?: string | undefined;
    TWILIO_AUTH_TOKEN?: string | undefined;
    TWILIO_PHONE_NUMBER?: string | undefined;
}, {
    DATABASE_URL: string;
    NEXTAUTH_SECRET: string;
    NEXTAUTH_URL: string;
    CORS_ORIGINS: string;
    STRIPE_SECRET_KEY: string;
    STRIPE_WEBHOOK_SECRET: string;
    RESEND_API_KEY: string;
    OPENAI_API_KEY: string;
    OPENAI_MODEL?: string | undefined;
    NODE_ENV?: "development" | "production" | "test" | undefined;
    PORT?: number | undefined;
    SENTRY_DSN?: string | undefined;
    TWILIO_ACCOUNT_SID?: string | undefined;
    TWILIO_AUTH_TOKEN?: string | undefined;
    TWILIO_PHONE_NUMBER?: string | undefined;
}>;
export type Env = z.infer<typeof envSchema>;
export declare function validateEnv(): Env;
export declare const env: {
    DATABASE_URL: string;
    NEXTAUTH_SECRET: string;
    NEXTAUTH_URL: string;
    CORS_ORIGINS: string[];
    STRIPE_SECRET_KEY: string;
    STRIPE_WEBHOOK_SECRET: string;
    RESEND_API_KEY: string;
    OPENAI_API_KEY: string;
    OPENAI_MODEL: string;
    NODE_ENV: "development" | "production" | "test";
    PORT: number;
    SENTRY_DSN?: string | undefined;
    TWILIO_ACCOUNT_SID?: string | undefined;
    TWILIO_AUTH_TOKEN?: string | undefined;
    TWILIO_PHONE_NUMBER?: string | undefined;
};
export declare const getEnv: () => {
    DATABASE_URL: string;
    NEXTAUTH_SECRET: string;
    NEXTAUTH_URL: string;
    CORS_ORIGINS: string[];
    STRIPE_SECRET_KEY: string;
    STRIPE_WEBHOOK_SECRET: string;
    RESEND_API_KEY: string;
    OPENAI_API_KEY: string;
    OPENAI_MODEL: string;
    NODE_ENV: "development" | "production" | "test";
    PORT: number;
    SENTRY_DSN?: string | undefined;
    TWILIO_ACCOUNT_SID?: string | undefined;
    TWILIO_AUTH_TOKEN?: string | undefined;
    TWILIO_PHONE_NUMBER?: string | undefined;
};
export {};
//# sourceMappingURL=env.d.ts.map